server:
  port: 8080

spring:
  application:
    name: spring-security-client
  jpa:
    hibernate:
     ddl-auto: create-drop
    show-sql: true
  datasource:
   url: jdbc:mysql://localhost:3306/user-registration
   username: root
   password: admin
   driver-class-name: com.mysql.cj.jdbc.Driver
   database-platform: org.hibernate.dialect.MySQLDialect